language: r
sudo: false
cache: packages

repos:
  CRAN: https://cloud.r-project.org

env: NOT_CRAN="true"

branches:
  only:
    - master
    - release
    - dev
    
notifications:
  email:
    on_success: change
    on_failure: change



